package com.models;
// Generated Oct 24, 2010 10:46:46 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Icons generated by hbm2java
 */
@Entity
@Table(name="icons"
    ,catalog="eventlas_events"
)
public class Icons  implements java.io.Serializable {


     private Integer id;
     private String icon;
     private Set<Venues> venueses = new HashSet<Venues>(0);
     private Set<Events> eventses = new HashSet<Events>(0);
     private String name;

    public Icons() {
    }

	
    public Icons(String icon) {
        this.icon = icon;
    }
    public Icons(String icon, Set<Venues> venueses, Set<Events> eventses) {
       this.icon = icon;
       this.venueses = venueses;
       this.eventses = eventses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    
    @Column(name="icon", nullable=false, length=32)
    public String getIcon() {
        return this.icon;
    }
    
    public void setIcon(String icon) {
        this.icon = icon;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="icons")
    public Set<Venues> getVenueses() {
        return this.venueses;
    }
    
    public void setVenueses(Set<Venues> venueses) {
        this.venueses = venueses;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="icons")
    public Set<Events> getEventses() {
        return this.eventses;
    }
    
    public void setEventses(Set<Events> eventses) {
        this.eventses = eventses;
    }
    @Column(name="name")
    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }





}


