package com.models;
// Generated Oct 24, 2010 10:46:46 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Location generated by hbm2java
 */
@Entity
@Table(name="location"
    ,catalog="eventlas_events"
    , uniqueConstraints = @UniqueConstraint(columnNames="hashid") 
)
public class Location  implements java.io.Serializable {


     private Integer id;
     private float longitude;
     private float latitude;
     private String hashid;
     private Set<Events> eventses = new HashSet<Events>(0);
     private Set<Venues> venueses = new HashSet<Venues>(0);
     

    public Location() {
    }

	
    public Location(float longitude, float latitude, String hashid) {
        this.longitude = longitude;
        this.latitude = latitude;
        this.hashid = hashid;
    }
    public Location(float longitude, float latitude, String hashid, Set<Events> eventses, Set<Venues> venueses) {
       this.longitude = longitude;
       this.latitude = latitude;
       this.hashid = hashid;
       this.eventses = eventses;
       this.venueses = venueses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    
    @Column(name="longitude", nullable=false, precision=10, scale=6)
    public float getLongitude() {
        return this.longitude;
    }
    
    public void setLongitude(float longitude) {
        this.longitude = longitude;
    }
    
    @Column(name="latitude", nullable=false, precision=10, scale=6)
    public float getLatitude() {
        return this.latitude;
    }
    
    public void setLatitude(float latitude) {
        this.latitude = latitude;
    }
    
    @Column(name="hashid", unique=true, nullable=false, length=32)
    public String getHashid() {
        return this.hashid;
    }
    
    public void setHashid(String hashid) {
        this.hashid = hashid;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="location")
    public Set<Events> getEventses() {
        return this.eventses;
    }
    
    public void setEventses(Set<Events> eventses) {
        this.eventses = eventses;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="location")
    public Set<Venues> getVenueses() {
        return this.venueses;
    }
    
    public void setVenueses(Set<Venues> venueses) {
        this.venueses = venueses;
    }
  




}


