package com.models;
// Generated Oct 24, 2010 10:46:46 PM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Usersgroups generated by hbm2java
 */
@Entity
@Table(name="usersgroups"
    ,catalog="eventlas_events"
)
public class Usersgroups  implements java.io.Serializable {


     private Integer id;
     private Groups groups;
     private Users usersByGroupmemberid;
     private Users usersByUserid;

    public Usersgroups() {
    }

    public Usersgroups(Groups groups, Users usersByGroupmemberid, Users usersByUserid) {
       this.groups = groups;
       this.usersByGroupmemberid = usersByGroupmemberid;
       this.usersByUserid = usersByUserid;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="groupid", nullable=false)
    public Groups getGroups() {
        return this.groups;
    }
    
    public void setGroups(Groups groups) {
        this.groups = groups;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="groupmemberid", nullable=false)
    public Users getUsersByGroupmemberid() {
        return this.usersByGroupmemberid;
    }
    
    public void setUsersByGroupmemberid(Users usersByGroupmemberid) {
        this.usersByGroupmemberid = usersByGroupmemberid;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="userid", nullable=false)
    public Users getUsersByUserid() {
        return this.usersByUserid;
    }
    
    public void setUsersByUserid(Users usersByUserid) {
        this.usersByUserid = usersByUserid;
    }




}


