package com.models;
// Generated Oct 24, 2010 10:46:46 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Visibility generated by hbm2java
 */
@Entity
@Table(name="visibility"
    ,catalog="eventlas_events"
)
public class Visibility  implements java.io.Serializable {


     private Integer id;
     private String privacylevel;
     private Set<Events> eventses = new HashSet<Events>(0);

    public Visibility() {
    }

    public Visibility(String privacylevel, Set<Events> eventses) {
       this.privacylevel = privacylevel;
       this.eventses = eventses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    
    @Column(name="privacylevel", length=64)
    public String getPrivacylevel() {
        return this.privacylevel;
    }
    
    public void setPrivacylevel(String privacylevel) {
        this.privacylevel = privacylevel;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="visibility")
    public Set<Events> getEventses() {
        return this.eventses;
    }
    
    public void setEventses(Set<Events> eventses) {
        this.eventses = eventses;
    }




}


